name: freud_ai
description: "Sukun 🌙 - Arabic for 'Calm' - Your Mental Health & Therapy Companion"
publish_to: 'none'

version: 0.8.5+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  page_transition: ^2.2.1
  device_preview: ^1.2.0
  vector_graphics: ^1.1.19
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/svgs/
    - assets/images/svgs/light/
    - assets/images/svgs/dark/
  fonts:
    - family: urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/urbanist/Urbanist-Black.ttf
          weight: 900
