import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HealthJournalYourEntries(),
        ]),
      ),
    );
  }
}

class HealthJournalYourEntries extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFF7F3F2),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 54,
                                  height: 21,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 732,
                child: Container(
                  width: 375,
                  height: 80,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF7F3F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 10,
                                        top: 12,
                                        child: Container(
                                          width: 4,
                                          height: 4,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFF4B3425),
                                              ),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 7,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 11,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(width: 24, height: 24, child: Stack()),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 311,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 5,
                                        top: 13,
                                        child: Container(
                                          width: 14,
                                          height: 14,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 8,
                                        top: 5,
                                        child: Container(
                                          width: 8,
                                          height: 8,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                              borderRadius: BorderRadius.circular(1234),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 156,
                        top: -32,
                        child: Container(
                          width: 64,
                          height: 64,
                          padding: const EdgeInsets.all(16),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF9BB068),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x7F9BB068),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 60,
                child: Container(
                  width: 343,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 12,
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              color: const Color(0xFF4B3425),
                            ),
                            borderRadius: BorderRadius.circular(1234),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 27,
                                    top: 21,
                                    child: Container(
                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                      width: 18,
                                      height: 18,
                                      decoration: ShapeDecoration(
                                        shape: OvalBorder(
                                          side: BorderSide(
                                            width: 2,
                                            strokeAlign: BorderSide.strokeAlignCenter,
                                            color: const Color(0xFF4B3425),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 132,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  spacing: 32,
                  children: [
                    Container(
                      width: 343,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 16,
                        children: [
                          Expanded(
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              spacing: 8,
                              children: [
                                SizedBox(
                                  width: 216,
                                  child: Text(
                                    'Your Entries',
                                    style: TextStyle(
                                      color: const Color(0xFF4B3425),
                                      fontSize: 36,
                                      fontFamily: 'Urbanist',
                                      fontWeight: FontWeight.w800,
                                      height: 1.22,
                                      letterSpacing: -1.08,
                                    ),
                                  ),
                                ),
                                Text(
                                  'Document your Mental Journal.',
                                  style: TextStyle(
                                    color: const Color(0xA31F160F),
                                    fontSize: 18,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w500,
                                    height: 1.60,
                                    letterSpacing: -0.18,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Container(
                            width: 64,
                            height: 64,
                            decoration: ShapeDecoration(
                              color: const Color(0xFF4B3425),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(1234),
                              ),
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.center,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Container(width: 24, height: 24, child: Stack()),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      spacing: 12,
                      children: [
                        Container(
                          width: 343,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 131,
                            children: [
                              Text(
                                'All Journals',
                                style: TextStyle(
                                  color: const Color(0xFF4B3425),
                                  fontSize: 18,
                                  fontFamily: 'Urbanist',
                                  fontWeight: FontWeight.w800,
                                  letterSpacing: -0.18,
                                ),
                              ),
                              Container(
                                height: 32,
                                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFF4B3425),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 10,
                                  children: [
                                    Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 8,
                                      children: [
                                        Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 4,
                                          children: [
                                            Container(
                                              width: 20,
                                              height: 20,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 2.50,
                                                    top: 5,
                                                    child: Container(
                                                      width: 15,
                                                      height: 11.67,
                                                      decoration: ShapeDecoration(
                                                        shape: RoundedRectangleBorder(
                                                          side: BorderSide(
                                                            width: 1.67,
                                                            strokeAlign: BorderSide.strokeAlignCenter,
                                                            color: const Color(0xFF4B3425),
                                                          ),
                                                          borderRadius: BorderRadius.circular(1028.33),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 9.17,
                                                    top: 10.83,
                                                    child: Container(
                                                      width: 1.67,
                                                      height: 1.67,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: RoundedRectangleBorder(
                                                          borderRadius: BorderRadius.circular(1028.33),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 12.50,
                                                    top: 10.83,
                                                    child: Container(
                                                      width: 1.67,
                                                      height: 1.67,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: RoundedRectangleBorder(
                                                          borderRadius: BorderRadius.circular(1028.33),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 5.83,
                                                    top: 10.83,
                                                    child: Container(
                                                      width: 1.67,
                                                      height: 1.67,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: RoundedRectangleBorder(
                                                          borderRadius: BorderRadius.circular(1028.33),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            Text(
                                              'Newest',
                                              style: TextStyle(
                                                color: const Color(0xFF4B3425),
                                                fontSize: 14,
                                                fontFamily: 'Urbanist',
                                                fontWeight: FontWeight.w600,
                                                letterSpacing: -0.14,
                                              ),
                                            ),
                                          ],
                                        ),
                                        Container(width: 20, height: 20, child: Stack()),
                                      ],
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 8,
                          children: [
                            Container(
                              padding: const EdgeInsets.all(16),
                              clipBehavior: Clip.antiAlias,
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(32),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x0C4B3425),
                                    blurRadius: 16,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 10,
                                children: [
                                  Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 89,
                                    children: [
                                      Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 31,
                                          children: [
                                            Container(
                                              width: 48,
                                              height: 48,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFF9BB068),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(16),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                spacing: 10,
                                                children: [
                                                  Container(width: 24, height: 24, child: Stack()),
                                                ],
                                              ),
                                            ),
                                            Container(width: 24, height: 24, child: Stack()),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: 189,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 8,
                                          children: [
                                            Container(
                                              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                                              clipBehavior: Clip.antiAlias,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFFF2F4EA),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(100),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  Text(
                                                    'MOOD: HAPPY',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFF9BB068),
                                                      fontSize: 10,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w800,
                                                      letterSpacing: 1,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'I’m grateful for my life. Truly',
                                                style: TextStyle(
                                                  color: const Color(0xFF4B3425),
                                                  fontSize: 18,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.18,
                                                ),
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'Today, I just had a revelation. It was that ...',
                                                style: TextStyle(
                                                  color: const Color(0xA31F160F),
                                                  fontSize: 12,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.60,
                                                  letterSpacing: -0.12,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.all(16),
                              clipBehavior: Clip.antiAlias,
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(32),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x0C4B3425),
                                    blurRadius: 16,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 10,
                                children: [
                                  Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 89,
                                    children: [
                                      Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 31,
                                          children: [
                                            Container(
                                              width: 48,
                                              height: 48,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFFFE804B),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(16),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                spacing: 10,
                                                children: [
                                                  Container(width: 24, height: 24, child: Stack()),
                                                ],
                                              ),
                                            ),
                                            Container(width: 24, height: 24, child: Stack()),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: 189,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 8,
                                          children: [
                                            Container(
                                              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                                              clipBehavior: Clip.antiAlias,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFFFEEFEA),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(100),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  Text(
                                                    'MOOD: ANGRY',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFFFE804B),
                                                      fontSize: 10,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w800,
                                                      letterSpacing: 1,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'F*** Everyone and everything else...',
                                                style: TextStyle(
                                                  color: const Color(0xFF4B3425),
                                                  fontSize: 18,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.18,
                                                ),
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'I just don’t like the b***** at my school.',
                                                style: TextStyle(
                                                  color: const Color(0xA31F160F),
                                                  fontSize: 12,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.60,
                                                  letterSpacing: -0.12,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.all(16),
                              clipBehavior: Clip.antiAlias,
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(32),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x0C4B3425),
                                    blurRadius: 16,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 10,
                                children: [
                                  Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 89,
                                    children: [
                                      Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 31,
                                          children: [
                                            Container(
                                              width: 48,
                                              height: 48,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFF9BB068),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(16),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                spacing: 10,
                                                children: [
                                                  Container(width: 24, height: 24, child: Stack()),
                                                ],
                                              ),
                                            ),
                                            Container(width: 24, height: 24, child: Stack()),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: 189,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 8,
                                          children: [
                                            Container(
                                              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                                              clipBehavior: Clip.antiAlias,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFFF2F4EA),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(100),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  Text(
                                                    'MOOD: HAPPY',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFF9BB068),
                                                      fontSize: 10,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w800,
                                                      letterSpacing: 1,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'I’m grateful for my life. Truly',
                                                style: TextStyle(
                                                  color: const Color(0xFF4B3425),
                                                  fontSize: 18,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.18,
                                                ),
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'Today, I just had a revelation. It was that ...',
                                                style: TextStyle(
                                                  color: const Color(0xA31F160F),
                                                  fontSize: 12,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.60,
                                                  letterSpacing: -0.12,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.all(16),
                              clipBehavior: Clip.antiAlias,
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(32),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x0C4B3425),
                                    blurRadius: 16,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 10,
                                children: [
                                  Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 89,
                                    children: [
                                      Container(
                                        width: double.infinity,
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 31,
                                          children: [
                                            Container(
                                              width: 48,
                                              height: 48,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFF9BB068),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(16),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                spacing: 10,
                                                children: [
                                                  Container(width: 24, height: 24, child: Stack()),
                                                ],
                                              ),
                                            ),
                                            Container(width: 24, height: 24, child: Stack()),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: 189,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 8,
                                          children: [
                                            Container(
                                              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                                              clipBehavior: Clip.antiAlias,
                                              decoration: ShapeDecoration(
                                                color: const Color(0xFFF2F4EA),
                                                shape: RoundedRectangleBorder(
                                                  borderRadius: BorderRadius.circular(100),
                                                ),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.center,
                                                crossAxisAlignment: CrossAxisAlignment.center,
                                                children: [
                                                  Text(
                                                    'MOOD: HAPPY',
                                                    textAlign: TextAlign.center,
                                                    style: TextStyle(
                                                      color: const Color(0xFF9BB068),
                                                      fontSize: 10,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w800,
                                                      letterSpacing: 1,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'I’m grateful for my life. Truly',
                                                style: TextStyle(
                                                  color: const Color(0xFF4B3425),
                                                  fontSize: 18,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w700,
                                                  letterSpacing: -0.18,
                                                ),
                                              ),
                                            ),
                                            SizedBox(
                                              width: 189,
                                              child: Text(
                                                'Today, I just had a revelation. It was that ...',
                                                style: TextStyle(
                                                  color: const Color(0xA31F160F),
                                                  fontSize: 12,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.60,
                                                  letterSpacing: -0.12,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      spacing: 12,
                      children: [
                        Container(
                          width: 343,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 131,
                            children: [
                              Text(
                                'Journal Stats',
                                style: TextStyle(
                                  color: const Color(0xFF4B3425),
                                  fontSize: 18,
                                  fontFamily: 'Urbanist',
                                  fontWeight: FontWeight.w800,
                                  letterSpacing: -0.18,
                                ),
                              ),
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 16,
                          children: [
                            Container(
                              width: 163,
                              padding: const EdgeInsets.all(16),
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(24),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x0C4B3425),
                                    blurRadius: 16,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: double.infinity,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 8,
                                      children: [
                                        Container(
                                          width: 48,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF2F4EA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(16),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Container(
                                                width: 24,
                                                height: 24,
                                                child: Stack(
                                                  children: [
                                                    Positioned(
                                                      left: 14,
                                                      top: 2,
                                                      child: Container(
                                                        width: 6,
                                                        height: 6,
                                                        decoration: ShapeDecoration(
                                                          shape: OvalBorder(
                                                            side: BorderSide(
                                                              width: 2,
                                                              strokeAlign: BorderSide.strokeAlignCenter,
                                                              color: const Color(0xFF9BB068),
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                        Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            spacing: 4,
                                            children: [
                                              Text(
                                                '81/365',
                                                style: TextStyle(
                                                  color: const Color(0xFF4B3425),
                                                  fontSize: 20,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w800,
                                                  letterSpacing: -0.20,
                                                ),
                                              ),
                                              Text(
                                                'Completed',
                                                style: TextStyle(
                                                  color: const Color(0x7A1F160F),
                                                  fontSize: 14,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w600,
                                                  letterSpacing: -0.14,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 163,
                              padding: const EdgeInsets.all(16),
                              decoration: ShapeDecoration(
                                color: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(24),
                                ),
                                shadows: [
                                  BoxShadow(
                                    color: Color(0x0C4B3425),
                                    blurRadius: 16,
                                    offset: Offset(0, 8),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: double.infinity,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.start,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      spacing: 8,
                                      children: [
                                        Container(
                                          width: 48,
                                          height: 48,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF7F3F2),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(16),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 10,
                                            children: [
                                              Container(width: 24, height: 24, child: Stack()),
                                            ],
                                          ),
                                        ),
                                        Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.start,
                                            spacing: 4,
                                            children: [
                                              Text(
                                                'Neutral',
                                                style: TextStyle(
                                                  color: const Color(0xFF4B3425),
                                                  fontSize: 20,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w800,
                                                  letterSpacing: -0.20,
                                                ),
                                              ),
                                              Text(
                                                'Emotion',
                                                style: TextStyle(
                                                  color: const Color(0x7A1F160F),
                                                  fontSize: 14,
                                                  fontFamily: 'Urbanist',
                                                  fontWeight: FontWeight.w600,
                                                  letterSpacing: -0.14,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}