import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HealthJournal(),
        ]),
      ),
    );
  }
}

class HealthJournal extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF926247),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -293,
                top: 346,
                child: Container(
                  width: 960,
                  height: 960,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2236.62),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0C4B3425),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x0C4B3425),
                        blurRadius: 38,
                        offset: Offset(0, -17),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x0A4B3425),
                        blurRadius: 69,
                        offset: Offset(0, -69),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x074B3425),
                        blurRadius: 93,
                        offset: Offset(0, -154),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x024B3425),
                        blurRadius: 110,
                        offset: Offset(0, -274),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x004B3425),
                        blurRadius: 120,
                        offset: Offset(0, -428),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 308,
                        top: 64,
                        child: Container(
                          width: 343,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 131,
                            children: [
                              Text(
                                'Journal History',
                                style: TextStyle(
                                  color: const Color(0xFF4B3425),
                                  fontSize: 18,
                                  fontFamily: 'Urbanist',
                                  fontWeight: FontWeight.w800,
                                  letterSpacing: -0.18,
                                ),
                              ),
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 308,
                        top: 100,
                        child: Container(
                          width: 342,
                          child: Wrap(
                            alignment: WrapAlignment.start,
                            runAlignment: WrapAlignment.center,
                            spacing: 8,
                            runSpacing: 8,
                            children: [
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFE7DDD8),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFE7DDD8),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFE7DDD8),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFD4C1B9),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFD4C1B9),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFD4C1B9),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFD4C1B9),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF926247),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF9BB068),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF9BB068),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFFE804B),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF9BB068),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF926247),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF926247),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFD4C1B9),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFD4C1B9),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFE7DDD8),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFE7DDD8),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  color: const Color(0xFFE7DDD8),
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                              Container(
                                width: 42,
                                height: 42,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      color: const Color(0xFFD4C1B9),
                                    ),
                                    borderRadius: BorderRadius.circular(1234),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 308,
                        top: 316,
                        child: Container(
                          width: 343,
                          padding: const EdgeInsets.all(8),
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF7F3F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                spacing: 48,
                                children: [
                                  Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    spacing: 6,
                                    children: [
                                      Container(
                                        width: 8,
                                        height: 8,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFFE804B),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(1234),
                                          ),
                                        ),
                                      ),
                                      Text(
                                        'Negative',
                                        style: TextStyle(
                                          color: const Color(0xA31F160F),
                                          fontSize: 14,
                                          fontFamily: 'Urbanist',
                                          fontWeight: FontWeight.w700,
                                          letterSpacing: -0.14,
                                        ),
                                      ),
                                    ],
                                  ),
                                  Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    spacing: 6,
                                    children: [
                                      Container(
                                        width: 8,
                                        height: 8,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF926247),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(1234),
                                          ),
                                        ),
                                      ),
                                      Text(
                                        'Neutral',
                                        style: TextStyle(
                                          color: const Color(0xA31F160F),
                                          fontSize: 14,
                                          fontFamily: 'Urbanist',
                                          fontWeight: FontWeight.w700,
                                          letterSpacing: -0.14,
                                        ),
                                      ),
                                    ],
                                  ),
                                  Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    spacing: 6,
                                    children: [
                                      Container(
                                        width: 8,
                                        height: 8,
                                        clipBehavior: Clip.antiAlias,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFF9BB068),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(1234),
                                          ),
                                        ),
                                      ),
                                      Text(
                                        'Positive',
                                        style: TextStyle(
                                          color: const Color(0xA31F160F),
                                          fontSize: 14,
                                          fontFamily: 'Urbanist',
                                          fontWeight: FontWeight.w700,
                                          letterSpacing: -0.14,
                                        ),
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 306,
                child: Container(
                  width: 80,
                  height: 80,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4B3425),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 28,
                        top: 28,
                        child: Container(width: 24, height: 24, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 54,
                                  height: 21,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 732,
                child: Container(
                  width: 375,
                  height: 80,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF7F3F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 10,
                                        top: 12,
                                        child: Container(
                                          width: 4,
                                          height: 4,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFF4B3425),
                                              ),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 7,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 11,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(width: 24, height: 24, child: Stack()),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 311,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 5,
                                        top: 13,
                                        child: Container(
                                          width: 14,
                                          height: 14,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 8,
                                        top: 5,
                                        child: Container(
                                          width: 8,
                                          height: 8,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                              borderRadius: BorderRadius.circular(1234),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 156,
                        top: -32,
                        child: Container(
                          width: 64,
                          height: 64,
                          padding: const EdgeInsets.all(16),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF9BB068),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x7F9BB068),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 60,
                child: Container(
                  width: 343,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 12,
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 1, color: Colors.white),
                            borderRadius: BorderRadius.circular(1234),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 27,
                                    top: 21,
                                    child: Container(
                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                      width: 18,
                                      height: 18,
                                      decoration: ShapeDecoration(
                                        shape: OvalBorder(
                                          side: BorderSide(
                                            width: 2,
                                            strokeAlign: BorderSide.strokeAlignCenter,
                                            color: Colors.white,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(
                        width: 283,
                        child: Text(
                          'Health Journal',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Urbanist',
                            fontWeight: FontWeight.w800,
                            letterSpacing: -0.20,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 61,
                top: 148,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 12,
                  children: [
                    Text(
                      '34/365',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 72,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w800,
                        height: 1.11,
                        letterSpacing: -2.16,
                      ),
                    ),
                    Text(
                      'Journals this year. Keep it Up!',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 20,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w600,
                        letterSpacing: -0.20,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}