import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Mood(),
        ]),
      ),
    );
  }
}

class Mood extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 437,
                child: Stack(
                  children: [
                    Container(
                      width: 343,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 131,
                        children: [
                          Text(
                            'Mood Statistics',
                            style: TextStyle(
                              color: const Color(0xFF4B3425),
                              fontSize: 18,
                              fontFamily: 'Urbanist',
                              fontWeight: FontWeight.w800,
                              letterSpacing: -0.18,
                            ),
                          ),
                          Container(width: 24, height: 24, child: Stack()),
                        ],
                      ),
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.start,
                      spacing: 40,
                      children: [
                        Container(
                          width: 375,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7DDD8),
                              ),
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                        ),
                        Container(
                          width: 375,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7DDD8),
                              ),
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                        ),
                        Container(
                          width: 375,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7DDD8),
                              ),
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                        ),
                        Container(
                          width: 375,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7DDD8),
                              ),
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                        ),
                        Container(
                          width: 375,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7DDD8),
                              ),
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                        ),
                        Container(
                          width: 375,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE7DDD8),
                              ),
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                        ),
                      ],
                    ),
                    Container(
                      width: 343,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        spacing: 16,
                        children: [
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Mon',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Tue',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Wed',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Thu',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Fri',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Sat',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 10,
                              children: [
                                Text(
                                  'Sun',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0x7A1F160F),
                                    fontSize: 14,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w600,
                                    letterSpacing: -0.14,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    Positioned(
                      left: 16,
                      top: 160,
                      child: Container(
                        width: 36,
                        height: 80,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFE7DDD8),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 67,
                      top: 187,
                      child: Container(
                        width: 36,
                        height: 53,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFE7DDD8),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 118,
                      top: 80,
                      child: Container(
                        width: 36,
                        height: 160,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFFFCE5B),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 169,
                      top: 40,
                      child: Container(
                        width: 36,
                        height: 200,
                        decoration: ShapeDecoration(
                          color: const Color(0xFF9BB068),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 220,
                      top: 120,
                      child: Container(
                        width: 36,
                        height: 120,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFFE804B),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 271,
                      top: 201,
                      child: Container(
                        width: 36,
                        height: 39,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFE7DDD8),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 322,
                      top: 160,
                      child: Container(
                        width: 36,
                        height: 80,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFE7DDD8),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(1234),
                              topRight: Radius.circular(1234),
                            ),
                          ),
                        ),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 6,
                              top: 6,
                              child: Container(width: 24, height: 24, child: Stack()),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: -173,
                top: -307,
                child: Container(
                  width: 720,
                  height: 720,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE7DDD8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0CFFCE5C),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x07FFCE5C),
                        blurRadius: 71,
                        offset: Offset(0, 119),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 68,
                        top: 939,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          width: 874,
                          height: 582,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 246,
                        top: 439,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 32,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              children: [
                                SizedBox(
                                  width: 227,
                                  child: Text(
                                    'Your mood is',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF4B3425),
                                      fontSize: 20,
                                      fontFamily: 'Urbanist',
                                      fontWeight: FontWeight.w600,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                                Text(
                                  'Neutral',
                                  style: TextStyle(
                                    color: const Color(0xFF4B3425),
                                    fontSize: 72,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w800,
                                    height: 1.11,
                                    letterSpacing: -2.16,
                                  ),
                                ),
                              ],
                            ),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 16,
                              children: [
                                Container(width: 24, height: 24, child: Stack()),
                                Container(
                                  width: 96,
                                  height: 96,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFBDA193),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(4936),
                                    ),
                                  ),
                                  child: Stack(),
                                ),
                                Container(width: 24, height: 24, child: Stack()),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 54,
                                  height: 21,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 732,
                child: Container(
                  width: 375,
                  height: 80,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF7F3F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 10,
                                        top: 12,
                                        child: Container(
                                          width: 4,
                                          height: 4,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFF4B3425),
                                              ),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 7,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 11,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(width: 24, height: 24, child: Stack()),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 311,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 5,
                                        top: 13,
                                        child: Container(
                                          width: 14,
                                          height: 14,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 8,
                                        top: 5,
                                        child: Container(
                                          width: 8,
                                          height: 8,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                              borderRadius: BorderRadius.circular(1234),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 156,
                        top: -32,
                        child: Container(
                          width: 64,
                          height: 64,
                          padding: const EdgeInsets.all(16),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF9BB068),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x7F9BB068),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 60,
                child: Container(
                  width: 343,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 12,
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              color: const Color(0xFF4B3425),
                            ),
                            borderRadius: BorderRadius.circular(1234),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 27,
                                    top: 21,
                                    child: Container(
                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                      width: 18,
                                      height: 18,
                                      decoration: ShapeDecoration(
                                        shape: OvalBorder(
                                          side: BorderSide(
                                            width: 2,
                                            strokeAlign: BorderSide.strokeAlignCenter,
                                            color: const Color(0xFF4B3425),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(
                        width: 195,
                        child: Text(
                          'Mood',
                          style: TextStyle(
                            color: const Color(0xFF4B3425),
                            fontSize: 20,
                            fontFamily: 'Urbanist',
                            fontWeight: FontWeight.w800,
                            letterSpacing: -0.20,
                          ),
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                        clipBehavior: Clip.antiAlias,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFD4C1B9),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(100),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'LEVEL 3',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF926247),
                                fontSize: 12,
                                fontFamily: 'Urbanist',
                                fontWeight: FontWeight.w800,
                                letterSpacing: 1.20,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}