import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SleepQuality(),
        ]),
      ),
    );
  }
}

class SleepQuality extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFF7F3F2),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 16,
                top: 465,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  spacing: 12,
                  children: [
                    Container(
                      width: 343,
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        spacing: 131,
                        children: [
                          Text(
                            'Sleep Stats',
                            style: TextStyle(
                              color: const Color(0xFF4B3425),
                              fontSize: 18,
                              fontFamily: 'Urbanist',
                              fontWeight: FontWeight.w800,
                              letterSpacing: -0.18,
                            ),
                          ),
                          Container(width: 24, height: 24, child: Stack()),
                        ],
                      ),
                    ),
                    Container(
                      width: 344,
                      child: Wrap(
                        alignment: WrapAlignment.start,
                        runAlignment: WrapAlignment.start,
                        spacing: 16,
                        runSpacing: 16,
                        children: [
                          Container(
                            width: 164,
                            padding: const EdgeInsets.all(16),
                            clipBehavior: Clip.antiAlias,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(24),
                              ),
                              shadows: [
                                BoxShadow(
                                  color: Color(0x0C4B3425),
                                  blurRadius: 16,
                                  offset: Offset(0, 8),
                                  spreadRadius: 0,
                                )
                              ],
                            ),
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  width: double.infinity,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 16,
                                    children: [
                                      Container(
                                        width: 40,
                                        height: 40,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFF7F3F2),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 10,
                                          children: [
                                            Container(width: 24, height: 24, child: Stack()),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: double.infinity,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 4,
                                          children: [
                                            Text(
                                              'Last Sleep',
                                              style: TextStyle(
                                                color: const Color(0xFF4B3425),
                                                fontSize: 16,
                                                fontFamily: 'Urbanist',
                                                fontWeight: FontWeight.w700,
                                                letterSpacing: -0.16,
                                              ),
                                            ),
                                            Container(
                                              width: double.infinity,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.start,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                spacing: 4,
                                                children: [
                                                  Text(
                                                    '19:55',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B3425),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                  Text(
                                                    'PM',
                                                    style: TextStyle(
                                                      color: const Color(0xFF926247),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Container(
                            width: 164,
                            padding: const EdgeInsets.all(16),
                            clipBehavior: Clip.antiAlias,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(24),
                              ),
                              shadows: [
                                BoxShadow(
                                  color: Color(0x0C4B3425),
                                  blurRadius: 16,
                                  offset: Offset(0, 8),
                                  spreadRadius: 0,
                                )
                              ],
                            ),
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  width: double.infinity,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 16,
                                    children: [
                                      Container(
                                        width: 40,
                                        height: 40,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFF7F3F2),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 10,
                                          children: [
                                            Container(
                                              width: 24,
                                              height: 24,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 0,
                                                    top: -8,
                                                    child: Container(
                                                      width: 24,
                                                      height: 24,
                                                      decoration: ShapeDecoration(
                                                        shape: OvalBorder(
                                                          side: BorderSide(
                                                            width: 2,
                                                            strokeAlign: BorderSide.strokeAlignCenter,
                                                            color: const Color(0xFF4B3425),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 7,
                                                    top: 16,
                                                    child: Container(
                                                      width: 10,
                                                      height: 10,
                                                      decoration: ShapeDecoration(
                                                        shape: OvalBorder(
                                                          side: BorderSide(
                                                            width: 2,
                                                            strokeAlign: BorderSide.strokeAlignCenter,
                                                            color: const Color(0xFF4B3425),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: double.infinity,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 4,
                                          children: [
                                            Text(
                                              'Start Sleeping',
                                              style: TextStyle(
                                                color: const Color(0xFF4B3425),
                                                fontSize: 16,
                                                fontFamily: 'Urbanist',
                                                fontWeight: FontWeight.w700,
                                                letterSpacing: -0.16,
                                              ),
                                            ),
                                            Container(
                                              width: double.infinity,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.start,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                spacing: 4,
                                                children: [
                                                  Text(
                                                    '23:55',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B3425),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                  Text(
                                                    'PM',
                                                    style: TextStyle(
                                                      color: const Color(0xFF926247),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    Container(
                      width: 344,
                      child: Wrap(
                        alignment: WrapAlignment.start,
                        runAlignment: WrapAlignment.start,
                        spacing: 16,
                        runSpacing: 16,
                        children: [
                          Container(
                            width: 164,
                            padding: const EdgeInsets.all(16),
                            clipBehavior: Clip.antiAlias,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(24),
                              ),
                              shadows: [
                                BoxShadow(
                                  color: Color(0x0C4B3425),
                                  blurRadius: 16,
                                  offset: Offset(0, 8),
                                  spreadRadius: 0,
                                )
                              ],
                            ),
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  width: double.infinity,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 16,
                                    children: [
                                      Container(
                                        width: 40,
                                        height: 40,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFF7F3F2),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 10,
                                          children: [
                                            Container(
                                              width: 24,
                                              height: 24,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: 6,
                                                    top: 6,
                                                    child: Container(
                                                      width: 12,
                                                      height: 12,
                                                      decoration: ShapeDecoration(
                                                        shape: OvalBorder(
                                                          side: BorderSide(
                                                            width: 2,
                                                            strokeAlign: BorderSide.strokeAlignCenter,
                                                            color: const Color(0xFF4B3425),
                                                          ),
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 11,
                                                    top: 2,
                                                    child: Container(
                                                      width: 2,
                                                      height: 2,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 11,
                                                    top: 20,
                                                    child: Container(
                                                      width: 2,
                                                      height: 2,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 22,
                                                    top: 11,
                                                    child: Container(
                                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                                                      width: 2,
                                                      height: 2,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 4,
                                                    top: 11,
                                                    child: Container(
                                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                                                      width: 2,
                                                      height: 2,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 17.66,
                                                    top: 4.22,
                                                    child: Container(
                                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.79),
                                                      width: 3,
                                                      height: 1,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 4.93,
                                                    top: 16.95,
                                                    child: Container(
                                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.79),
                                                      width: 3,
                                                      height: 1,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 7.05,
                                                    top: 4.93,
                                                    child: Container(
                                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(2.36),
                                                      width: 3,
                                                      height: 1,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                  Positioned(
                                                    left: 19.78,
                                                    top: 17.66,
                                                    child: Container(
                                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(2.36),
                                                      width: 3,
                                                      height: 1,
                                                      decoration: ShapeDecoration(
                                                        color: const Color(0xFF4B3425),
                                                        shape: OvalBorder(),
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: double.infinity,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 4,
                                          children: [
                                            Text(
                                              'Wake Up',
                                              style: TextStyle(
                                                color: const Color(0xFF4B3425),
                                                fontSize: 16,
                                                fontFamily: 'Urbanist',
                                                fontWeight: FontWeight.w700,
                                                letterSpacing: -0.16,
                                              ),
                                            ),
                                            Container(
                                              width: double.infinity,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.start,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                spacing: 4,
                                                children: [
                                                  Text(
                                                    '19:55',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B3425),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                  Text(
                                                    'PM',
                                                    style: TextStyle(
                                                      color: const Color(0xFF926247),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Container(
                            width: 164,
                            padding: const EdgeInsets.all(16),
                            clipBehavior: Clip.antiAlias,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(24),
                              ),
                              shadows: [
                                BoxShadow(
                                  color: Color(0x0C4B3425),
                                  blurRadius: 16,
                                  offset: Offset(0, 8),
                                  spreadRadius: 0,
                                )
                              ],
                            ),
                            child: Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Container(
                                  width: double.infinity,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    spacing: 16,
                                    children: [
                                      Container(
                                        width: 40,
                                        height: 40,
                                        decoration: ShapeDecoration(
                                          color: const Color(0xFFF7F3F2),
                                          shape: RoundedRectangleBorder(
                                            borderRadius: BorderRadius.circular(12),
                                          ),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 10,
                                          children: [
                                            Container(width: 24, height: 24, child: Stack()),
                                          ],
                                        ),
                                      ),
                                      Container(
                                        width: double.infinity,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 4,
                                          children: [
                                            Text(
                                              'Deep Sleep',
                                              style: TextStyle(
                                                color: const Color(0xFF4B3425),
                                                fontSize: 16,
                                                fontFamily: 'Urbanist',
                                                fontWeight: FontWeight.w700,
                                                letterSpacing: -0.16,
                                              ),
                                            ),
                                            Container(
                                              width: double.infinity,
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment: MainAxisAlignment.start,
                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                spacing: 4,
                                                children: [
                                                  Text(
                                                    '19:55',
                                                    style: TextStyle(
                                                      color: const Color(0xFF4B3425),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                  Text(
                                                    'PM',
                                                    style: TextStyle(
                                                      color: const Color(0xFF926247),
                                                      fontSize: 16,
                                                      fontFamily: 'Urbanist',
                                                      fontWeight: FontWeight.w600,
                                                      letterSpacing: -0.16,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: -173,
                top: -307,
                child: Container(
                  width: 720,
                  height: 720,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFA18EFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 222,
                        top: 463,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 24,
                          children: [
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 8,
                              children: [
                                Text(
                                  'Level 1',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 72,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w800,
                                    height: 1.11,
                                    letterSpacing: -2.16,
                                  ),
                                ),
                                Text(
                                  'You are Insomniac.',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 30,
                                    fontFamily: 'Urbanist',
                                    fontWeight: FontWeight.w800,
                                    height: 1.27,
                                    letterSpacing: -0.60,
                                  ),
                                ),
                              ],
                            ),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              spacing: 4,
                              children: [
                                Container(
                                  width: 52,
                                  height: 8,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(1234),
                                    ),
                                  ),
                                ),
                                Container(
                                  width: 52,
                                  height: 8,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Colors.white),
                                      borderRadius: BorderRadius.circular(1234),
                                    ),
                                  ),
                                ),
                                Container(
                                  width: 52,
                                  height: 8,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Colors.white),
                                      borderRadius: BorderRadius.circular(1234),
                                    ),
                                  ),
                                ),
                                Container(
                                  width: 52,
                                  height: 8,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Colors.white),
                                      borderRadius: BorderRadius.circular(1234),
                                    ),
                                  ),
                                ),
                                Container(
                                  width: 52,
                                  height: 8,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Colors.white),
                                      borderRadius: BorderRadius.circular(1234),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 54,
                                  height: 21,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 732,
                child: Container(
                  width: 375,
                  height: 80,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1234),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFF7F3F2),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 10,
                                        top: 12,
                                        child: Container(
                                          width: 4,
                                          height: 4,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFF4B3425),
                                              ),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 7,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 11,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15,
                                        top: 9,
                                        child: Container(
                                          width: 2,
                                          height: 2,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFD4C1B9),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(width: 24, height: 24, child: Stack()),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 311,
                        top: 16,
                        child: Container(
                          width: 48,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 12,
                                top: 12,
                                child: Container(
                                  width: 24,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 5,
                                        top: 13,
                                        child: Container(
                                          width: 14,
                                          height: 14,
                                          decoration: ShapeDecoration(
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 8,
                                        top: 5,
                                        child: Container(
                                          width: 8,
                                          height: 8,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 2,
                                                strokeAlign: BorderSide.strokeAlignCenter,
                                                color: const Color(0xFFD4C1B9),
                                              ),
                                              borderRadius: BorderRadius.circular(1234),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 156,
                        top: -32,
                        child: Container(
                          width: 64,
                          height: 64,
                          padding: const EdgeInsets.all(16),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF9BB068),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1234),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x7F9BB068),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 60,
                child: Container(
                  width: 343,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 12,
                    children: [
                      Container(
                        width: 48,
                        height: 48,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(width: 1, color: Colors.white),
                            borderRadius: BorderRadius.circular(1234),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 27,
                                    top: 21,
                                    child: Container(
                                      transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                      width: 18,
                                      height: 18,
                                      decoration: ShapeDecoration(
                                        shape: OvalBorder(
                                          side: BorderSide(
                                            width: 2,
                                            strokeAlign: BorderSide.strokeAlignCenter,
                                            color: Colors.white,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      SizedBox(
                        width: 283,
                        child: Text(
                          'Sleep Quality',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Urbanist',
                            fontWeight: FontWeight.w800,
                            letterSpacing: -0.20,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 148,
                top: 373,
                child: Container(
                  width: 80,
                  height: 80,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4B3425),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(1000),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 28,
                        top: 28,
                        child: Container(width: 24, height: 24, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
class SleepQuality extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF1F150F),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(40),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: -292,
                top: 346,
                child: Container(
                  width: 960,
                  height: 960,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4B3425),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2236.62),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0C3D4A26),
                        blurRadius: 0,
                        offset: Offset(0, 0),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x0C3D4A26),
                        blurRadius: 38,
                        offset: Offset(0, -17),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x0A3D4A26),
                        blurRadius: 69,
                        offset: Offset(0, -69),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x073D4A26),
                        blurRadius: 93,
                        offset: Offset(0, -154),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x023D4A26),
                        blurRadius: 110,
                        offset: Offset(0, -274),
                        spreadRadius: 0,
                      )BoxShadow(
                        color: Color(0x003D4A26),
                        blurRadius: 120,
                        offset: Offset(0, -428),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 375,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 54,
                                  height: 21,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(32),
                                    ),
                                  ),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 61,
                top: 68,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 24,
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                      clipBehavior: Clip.antiAlias,
                      decoration: ShapeDecoration(
                        color: const Color(0xFF6F2900),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(100),
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Text(
                            'ALARM AT 10:05',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFFE804B),
                              fontSize: 10,
                              fontFamily: 'Urbanist',
                              fontWeight: FontWeight.w800,
                              letterSpacing: 1,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Column(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      spacing: 16,
                      children: [
                        Text(
                          'Good Night, Shinomiya!',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 24,
                            fontFamily: 'Urbanist',
                            fontWeight: FontWeight.w800,
                            letterSpacing: -0.24,
                          ),
                        ),
                        Text(
                          '02:15',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 72,
                            fontFamily: 'Urbanist',
                            fontWeight: FontWeight.w800,
                            height: 1.11,
                            letterSpacing: -2.16,
                          ),
                        ),
                      ],
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      spacing: 8,
                      children: [
                        Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 8,
                          children: [
                            Container(
                              width: 20,
                              height: 20,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 2.50,
                                    top: 2.50,
                                    child: Container(
                                      width: 15,
                                      height: 15,
                                      decoration: ShapeDecoration(
                                        shape: RoundedRectangleBorder(
                                          side: BorderSide(
                                            width: 1.67,
                                            strokeAlign: BorderSide.strokeAlignCenter,
                                            color: Colors.white,
                                          ),
                                          borderRadius: BorderRadius.circular(1028.33),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 9.17,
                                    top: 0,
                                    child: Container(
                                      width: 13.33,
                                      height: 13.33,
                                      decoration: ShapeDecoration(
                                        shape: OvalBorder(
                                          side: BorderSide(
                                            width: 1.67,
                                            strokeAlign: BorderSide.strokeAlignCenter,
                                            color: Colors.white,
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Text(
                              'Sleep Duration ',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 14,
                                fontFamily: 'Urbanist',
                                fontWeight: FontWeight.w600,
                                letterSpacing: -0.14,
                              ),
                            ),
                          ],
                        ),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(width: 1, color: Colors.white),
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Text(
                                '2H 15M',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 14,
                                  fontFamily: 'Urbanist',
                                  fontWeight: FontWeight.w800,
                                  letterSpacing: 1.40,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 0,
                top: 726,
                child: Container(
                  width: 375,
                  height: 86,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 131,
                        top: 21,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 8,
                          children: [
                            Container(width: 24, height: 24, child: Stack()),
                            Text(
                              'Swipe to Wake Up',
                              style: TextStyle(
                                color: const Color(0xFF4B3425),
                                fontSize: 14,
                                fontFamily: 'Urbanist',
                                fontWeight: FontWeight.w700,
                                letterSpacing: -0.14,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}